import { useEffect, useMemo, useState } from 'react';
import ToolLayout from '../../components/ToolLayout';
import { CodeIcon, CompressIcon, CalculatorIcon, ImageIcon, KeyIcon, LinkIcon, PdfDocIcon, ReceiptIcon, TextIcon, TrendingUpIcon } from '../../components/icons';
import { downloadBlob, downloadBytes } from '../../lib/fileHelpers';
import { PDFDocument } from 'pdf-lib';
import { generateQrCodePng } from '../../lib/qrTools';

export type ExpandedToolKind =
  | 'code-formatter' | 'sql-formatter' | 'regex-tester' | 'jwt-decoder' | 'timestamp-converter'
  | 'csv-json-converter' | 'markdown-editor' | 'password-strength' | 'file-checksum'
  | 'image-cropper' | 'pdf-page-cropper' | 'profit-margin' | 'mortgage-amortization'
  | 'fuel-cost' | 'unit-price' | 'utm-builder' | 'meta-tag-generator' | 'url-slug-generator'
  | 'invoice-generator' | 'pomodoro-timer' | 'prime-checker' | 'fraction-calculator'
  | 'qr-logo-generator' | 'favicon-generator' | 'pdf-fill-sign';

const definitions: Record<ExpandedToolKind, { title: string; description: string; seo: string; icon: typeof CodeIcon }> = {
  'code-formatter': { title: 'Code Formatter', description: 'Format JSON, HTML, CSS, JavaScript and Markdown locally in your browser.', seo: 'Free browser-based code formatter for JSON, HTML, CSS, JavaScript and Markdown.', icon: CodeIcon },
  'sql-formatter': { title: 'SQL Formatter', description: 'Make SQL queries readable with indentation and normalized keywords.', seo: 'Free SQL formatter and beautifier that formats queries locally in your browser.', icon: CodeIcon },
  'regex-tester': { title: 'Regex Tester', description: 'Test regular expressions with match highlighting and capture groups.', seo: 'Free regular expression tester with matches, capture groups and replacement preview.', icon: CodeIcon },
  'jwt-decoder': { title: 'JWT Decoder', description: 'Decode JSON Web Token headers and payloads without sending them anywhere.', seo: 'Free local JWT decoder for inspecting token headers and payloads. Signature verification is not performed.', icon: KeyIcon },
  'timestamp-converter': { title: 'Unix Timestamp Converter', description: 'Convert Unix seconds or milliseconds to readable dates and back.', seo: 'Free Unix timestamp converter for seconds, milliseconds, UTC and local dates.', icon: LinkIcon },
  'csv-json-converter': { title: 'CSV JSON Converter', description: 'Convert tabular CSV data to JSON or JSON arrays to CSV locally.', seo: 'Free CSV to JSON and JSON to CSV converter with browser-only processing.', icon: CodeIcon },
  'markdown-editor': { title: 'Markdown Editor', description: 'Write Markdown, preview the rendered result, and download your document.', seo: 'Free online Markdown editor with live preview and local browser processing.', icon: TextIcon },
  'password-strength': { title: 'Password Strength Checker', description: 'Evaluate password length, variety and common weaknesses locally.', seo: 'Private password strength checker that evaluates passwords in your browser.', icon: KeyIcon },
  'file-checksum': { title: 'File Checksum Generator', description: 'Generate SHA-256, SHA-384 and SHA-512 checksums for local files.', seo: 'Free file checksum generator for SHA-256, SHA-384 and SHA-512 hashes.', icon: CompressIcon },
  'image-cropper': { title: 'Image Cropper', description: 'Crop an image to custom dimensions and download the result locally.', seo: 'Free image cropper with custom dimensions and browser-only processing.', icon: ImageIcon },
  'pdf-page-cropper': { title: 'PDF Page Cropper', description: 'Crop PDF page margins to remove scanner borders and excess whitespace.', seo: 'Free PDF page cropper for trimming margins and scanner borders in your browser.', icon: PdfDocIcon },
  'profit-margin': { title: 'Profit Margin Calculator', description: 'Calculate profit, markup, margin and selling price from your costs.', seo: 'Free profit margin and markup calculator for products and services.', icon: TrendingUpIcon },
  'mortgage-amortization': { title: 'Mortgage Amortization Calculator', description: 'View monthly payments and a full principal versus interest schedule.', seo: 'Free mortgage amortization calculator with payment schedule and interest breakdown.', icon: CalculatorIcon },
  'fuel-cost': { title: 'Fuel Cost Calculator', description: 'Estimate trip fuel cost from distance, mileage and fuel price.', seo: 'Free fuel cost calculator for estimating road trip and commute expenses.', icon: CalculatorIcon },
  'unit-price': { title: 'Unit Price Calculator', description: 'Compare prices by weight, volume, length or item count.', seo: 'Free unit price calculator for comparing products by quantity and measurement.', icon: CalculatorIcon },
  'utm-builder': { title: 'UTM Builder', description: 'Create campaign URLs with source, medium, campaign and content tags.', seo: 'Free UTM campaign URL builder for marketing links, processed locally.', icon: LinkIcon },
  'meta-tag-generator': { title: 'Meta Tag Generator', description: 'Generate SEO title, description, Open Graph and Twitter card markup.', seo: 'Free SEO meta tag and Open Graph generator for websites.', icon: CodeIcon },
  'url-slug-generator': { title: 'URL Slug Generator', description: 'Convert titles into clean, lowercase, search-friendly URL slugs.', seo: 'Free URL slug generator for clean SEO-friendly page URLs.', icon: LinkIcon },
  'invoice-generator': { title: 'Invoice Generator', description: 'Create a simple invoice and download it as a print-ready document.', seo: 'Free invoice generator for freelancers and small businesses with local browser processing.', icon: ReceiptIcon },
  'pomodoro-timer': { title: 'Pomodoro Timer', description: 'Focus in timed work and break sessions without an account.', seo: 'Free Pomodoro focus timer with work and break intervals.', icon: TrendingUpIcon },
  'prime-checker': { title: 'Prime Number Checker', description: 'Check whether a number is prime and inspect its factors.', seo: 'Free prime number checker and factorization tool.', icon: CalculatorIcon },
  'fraction-calculator': { title: 'Fraction Calculator', description: 'Add, subtract, multiply and divide fractions with simplified results.', seo: 'Free fraction calculator with simplified answers and mixed-number output.', icon: CalculatorIcon },
  'qr-logo-generator': { title: 'QR Code with Logo', description: 'Create a QR code with a centered logo for branded sharing.', seo: 'Free QR code generator with a centered logo, processed locally in your browser.', icon: ImageIcon },
  'favicon-generator': { title: 'Favicon Generator', description: 'Create common favicon and app icon sizes from one image.', seo: 'Free favicon and app icon generator for websites.', icon: ImageIcon },
  'pdf-fill-sign': { title: 'PDF Fill and Sign', description: 'Add a name, date or signature line to the first page of a PDF locally.', seo: 'Free browser-based PDF fill and sign tool for adding text to a PDF.', icon: PdfDocIcon },
};

const inputClass = 'mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-brand-500 focus:outline-none focus:ring-1 focus:ring-brand-500';
const areaClass = `${inputClass} min-h-56 resize-y font-mono`;

function parseNumber(value: string, fallback = 0) { const number = Number(value); return Number.isFinite(number) ? number : fallback; }
function gcd(first: number, second: number): number { let left = Math.abs(first); let right = Math.abs(second); while (right) [left, right] = [right, left % right]; return left || 1; }
function formatSql(source: string) { return source.trim().replace(/\s+/g, ' ').replace(/\s*,\s*/g, ',\n  ').replace(/\b(FROM|WHERE|GROUP BY|ORDER BY|HAVING|LIMIT|JOIN|LEFT JOIN|RIGHT JOIN|INNER JOIN|UNION|VALUES|SET)\b/gi, '\n$1').replace(/\b(AND|OR)\b/gi, '\n  $1').replace(/\b(SELECT|INSERT INTO|UPDATE|DELETE FROM|CREATE TABLE)\b/gi, (keyword) => keyword.toUpperCase()).trim(); }
function markdownToHtml(markdown: string) { return markdown.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/^### (.+)$/gm, '<h3>$1</h3>').replace(/^## (.+)$/gm, '<h2>$1</h2>').replace(/^# (.+)$/gm, '<h1>$1</h1>').replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/\*(.+?)\*/g, '<em>$1</em>').replace(/^[-*] (.+)$/gm, '<li>$1</li>').replace(/\n\n/g, '<p></p>').replace(/\n/g, '<br>'); }
function parseCsv(source: string) { return source.trim().split(/\r?\n/).map((line) => line.split(',').map((cell) => cell.trim().replace(/^"|"$/g, ''))); }
function jsonToCsv(source: string) { const rows = JSON.parse(source); if (!Array.isArray(rows) || !rows.length || typeof rows[0] !== 'object') throw new Error('Enter a JSON array of objects.'); const headers = Array.from(new Set(rows.flatMap((row) => Object.keys(row)))); return [headers.join(','), ...rows.map((row) => headers.map((header) => JSON.stringify(row[header] ?? '')).join(','))].join('\n'); }
function csvToJson(source: string) { const rows = parseCsv(source); if (rows.length < 2) throw new Error('Enter a header row and at least one data row.'); const [headers, ...data] = rows; return JSON.stringify(data.map((row) => Object.fromEntries(headers.map((header, index) => [header, row[index] ?? '']))), null, 2); }

export default function ExpandedTools({ kind }: { kind: ExpandedToolKind }) {
  const definition = definitions[kind];
  const Icon = definition.icon;
  const [source, setSource] = useState('');
  const [output, setOutput] = useState('');
  const [error, setError] = useState('');
  const [values, setValues] = useState<Record<string, string>>({});
  const setValue = (key: string, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const run = (action: () => string) => { try { setError(''); setOutput(action()); } catch (err) { setError(err instanceof Error ? err.message : 'Check the entered values.'); } };

  const result = useMemo(() => {
    if (kind === 'url-slug-generator') return source.toLowerCase().trim().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
    if (kind === 'markdown-editor') return markdownToHtml(source);
    return '';
  }, [kind, source]);

  const render = () => {
    if (kind === 'code-formatter') return <><select value={values.language ?? 'json'} onChange={(event) => setValue('language', event.target.value)} className={inputClass}><option value="json">JSON</option><option value="javascript">JavaScript</option><option value="typescript">TypeScript</option><option value="css">CSS</option><option value="html">HTML</option><option value="markdown">Markdown</option></select><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="Paste code here..." /><button type="button" onClick={() => run(() => { if ((values.language ?? 'json') === 'json') return JSON.stringify(JSON.parse(source), null, 2); return source.replace(/>\s*</g, '>\n<').replace(/;\s*/g, ';\n').replace(/\{\s*/g, '{\n  ').replace(/\s*\}/g, '\n}'); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Format code</button></>;
    if (kind === 'sql-formatter') return <><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="SELECT * FROM users WHERE active = true" /><button type="button" onClick={() => run(() => formatSql(source))} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Format SQL</button></>;
    if (kind === 'regex-tester') return <><input value={values.pattern ?? ''} onChange={(event) => setValue('pattern', event.target.value)} placeholder="Regular expression" className={inputClass} /><input value={values.flags ?? 'gi'} onChange={(event) => setValue('flags', event.target.value)} placeholder="Flags" className={inputClass} /><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="Test text" /><button type="button" onClick={() => run(() => { const expression = new RegExp(values.pattern ?? '', values.flags ?? 'gi'); const matches = Array.from(source.matchAll(expression)); return JSON.stringify(matches.map((match) => ({ match: match[0], index: match.index, groups: match.slice(1) })), null, 2); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Test expression</button></>;
    if (kind === 'jwt-decoder') return <><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="Paste a JWT token" /><button type="button" onClick={() => run(() => { const parts = source.split('.'); if (parts.length !== 3) throw new Error('A JWT must contain three dot-separated parts.'); const decode = (part: string) => JSON.parse(atob(part.replace(/-/g, '+').replace(/_/g, '/') + '='.repeat((4 - part.length % 4) % 4))); return JSON.stringify({ header: decode(parts[0]), payload: decode(parts[1]), note: 'Signature was not verified.' }, null, 2); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Decode JWT</button></>;
    if (kind === 'timestamp-converter') return <><input value={values.timestamp ?? ''} onChange={(event) => setValue('timestamp', event.target.value)} placeholder="Unix timestamp, blank for now" className={inputClass} /><button type="button" onClick={() => run(() => { const raw = values.timestamp?.trim(); const date = raw ? new Date((raw.length > 10 ? Number(raw) : Number(raw) * 1000)) : new Date(); if (Number.isNaN(date.getTime())) throw new Error('Enter a valid Unix timestamp.'); return JSON.stringify({ utc: date.toISOString(), local: date.toString(), seconds: Math.floor(date.getTime() / 1000), milliseconds: date.getTime() }, null, 2); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Convert timestamp</button></>;
    if (kind === 'csv-json-converter') return <><select value={values.direction ?? 'csv-json'} onChange={(event) => setValue('direction', event.target.value)} className={inputClass}><option value="csv-json">CSV to JSON</option><option value="json-csv">JSON to CSV</option></select><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="Paste CSV or JSON" /><button type="button" onClick={() => run(() => (values.direction ?? 'csv-json') === 'csv-json' ? csvToJson(source) : jsonToCsv(source))} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Convert data</button></>;
    if (kind === 'markdown-editor') return <><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="# Markdown document" /><div className="mt-4 rounded-xl border border-slate-200 bg-slate-50 p-4" dangerouslySetInnerHTML={{ __html: result }} /><button type="button" onClick={() => downloadBlob(new Blob([source], { type: 'text/markdown;charset=utf-8' }), 'document.md')} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Download Markdown</button></>;
    if (kind === 'password-strength') return <><input type="password" value={source} onChange={(event) => setSource(event.target.value)} className={inputClass} placeholder="Enter a password to evaluate locally" /><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm">{source ? `Score: ${Math.min(100, source.length * 5 + (/[A-Z]/.test(source) ? 15 : 0) + (/\d/.test(source) ? 15 : 0) + (/[^A-Za-z0-9]/.test(source) ? 15 : 0))}/100` : 'Enter a password to see its local score.'}</div></>;
    if (kind === 'profit-margin') return <><NumberField label="Cost" value={values.cost} onChange={(value) => setValue('cost', value)} /><NumberField label="Selling price" value={values.price} onChange={(value) => setValue('price', value)} /><button type="button" onClick={() => run(() => { const cost = parseNumber(values.cost); const price = parseNumber(values.price); if (cost <= 0 || price < 0) throw new Error('Enter positive amounts.'); return JSON.stringify({ profit: price - cost, marginPercent: ((price - cost) / price * 100).toFixed(2), markupPercent: ((price - cost) / cost * 100).toFixed(2) }, null, 2); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Calculate margin</button></>;
    if (kind === 'mortgage-amortization') return <><NumberField label="Principal" value={values.principal} onChange={(value) => setValue('principal', value)} /><NumberField label="Annual interest %" value={values.rate} onChange={(value) => setValue('rate', value)} /><NumberField label="Term in years" value={values.years} onChange={(value) => setValue('years', value)} /><button type="button" onClick={() => run(() => { const principal = parseNumber(values.principal); const months = parseNumber(values.years) * 12; const monthlyRate = parseNumber(values.rate) / 1200; const payment = monthlyRate ? principal * monthlyRate * (1 + monthlyRate) ** months / ((1 + monthlyRate) ** months - 1) : principal / months; let balance = principal; const rows = Array.from({ length: Math.min(months, 360) }, (_, index) => { const interest = balance * monthlyRate; const principalPaid = Math.min(payment - interest, balance); balance -= principalPaid; return `Month ${index + 1}: payment ${payment.toFixed(2)}, principal ${principalPaid.toFixed(2)}, interest ${interest.toFixed(2)}, balance ${Math.max(0, balance).toFixed(2)}`; }); return `Monthly payment: ${payment.toFixed(2)}\nTotal payment: ${(payment * months).toFixed(2)}\nTotal interest: ${(payment * months - principal).toFixed(2)}\n\n${rows.join('\n')}`; })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Build schedule</button></>;
    if (kind === 'fuel-cost') return <><NumberField label="Distance" value={values.distance} onChange={(value) => setValue('distance', value)} /><NumberField label="Vehicle economy (km/L)" value={values.economy} onChange={(value) => setValue('economy', value)} /><NumberField label="Fuel price per litre" value={values.fuelPrice} onChange={(value) => setValue('fuelPrice', value)} /><button type="button" onClick={() => run(() => `Fuel required: ${(parseNumber(values.distance) / parseNumber(values.economy)).toFixed(2)} L\nEstimated cost: ${(parseNumber(values.distance) / parseNumber(values.economy) * parseNumber(values.fuelPrice)).toFixed(2)}`)} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Calculate cost</button></>;
    if (kind === 'unit-price') return <><NumberField label="Price" value={values.price} onChange={(value) => setValue('price', value)} /><NumberField label="Quantity" value={values.quantity} onChange={(value) => setValue('quantity', value)} /><button type="button" onClick={() => run(() => `Unit price: ${(parseNumber(values.price) / parseNumber(values.quantity)).toFixed(4)}`)} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Calculate unit price</button></>;
    if (kind === 'utm-builder') return <><NumberField label="Base URL" value={values.url} onChange={(value) => setValue('url', value)} /><NumberField label="Campaign source" value={values.source} onChange={(value) => setValue('source', value)} /><NumberField label="Campaign medium" value={values.medium} onChange={(value) => setValue('medium', value)} /><NumberField label="Campaign name" value={values.campaign} onChange={(value) => setValue('campaign', value)} /><button type="button" onClick={() => run(() => { const url = new URL(values.url || 'https://example.com'); url.searchParams.set('utm_source', values.source || ''); url.searchParams.set('utm_medium', values.medium || ''); url.searchParams.set('utm_campaign', values.campaign || ''); return url.toString(); })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Build UTM URL</button></>;
    if (kind === 'meta-tag-generator') return <><NumberField label="Page title" value={values.title} onChange={(value) => setValue('title', value)} /><NumberField label="Description" value={values.description} onChange={(value) => setValue('description', value)} /><NumberField label="Canonical URL" value={values.url} onChange={(value) => setValue('url', value)} /><button type="button" onClick={() => run(() => `<title>${values.title ?? ''}</title>\n<meta name="description" content="${values.description ?? ''}">\n<link rel="canonical" href="${values.url ?? ''}">\n<meta property="og:title" content="${values.title ?? ''}">\n<meta property="og:description" content="${values.description ?? ''}">\n<meta property="og:url" content="${values.url ?? ''}">`)} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Generate tags</button></>;
    if (kind === 'url-slug-generator') return <><textarea value={source} onChange={(event) => setSource(event.target.value)} className={areaClass} placeholder="A page title becomes a clean URL slug" /><p className="mt-4 rounded-xl bg-slate-50 p-4 font-mono text-sm">{result}</p></>;
    if (kind === 'prime-checker') return <><NumberField label="Whole number" value={values.number} onChange={(value) => setValue('number', value)} /><button type="button" onClick={() => run(() => { const number = Math.floor(parseNumber(values.number)); if (number < 2) return `${number} is not prime.`; for (let divisor = 2; divisor * divisor <= number; divisor += 1) if (number % divisor === 0) return `${number} is not prime. Factor: ${divisor} x ${number / divisor}`; return `${number} is prime.`; })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Check number</button></>;
    if (kind === 'fraction-calculator') return <><NumberField label="First numerator" value={values.firstNumerator} onChange={(value) => setValue('firstNumerator', value)} /><NumberField label="First denominator" value={values.firstDenominator} onChange={(value) => setValue('firstDenominator', value)} /><select value={values.operator ?? '+'} onChange={(event) => setValue('operator', event.target.value)} className={inputClass}><option>+</option><option>-</option><option>*</option><option>/</option></select><NumberField label="Second numerator" value={values.secondNumerator} onChange={(value) => setValue('secondNumerator', value)} /><NumberField label="Second denominator" value={values.secondDenominator} onChange={(value) => setValue('secondDenominator', value)} /><button type="button" onClick={() => run(() => { const firstNumerator = parseNumber(values.firstNumerator); const firstDenominator = parseNumber(values.firstDenominator, 1); const secondNumerator = parseNumber(values.secondNumerator); const secondDenominator = parseNumber(values.secondDenominator, 1); const operator = values.operator ?? '+'; const numerator = operator === '+' ? firstNumerator * secondDenominator + secondNumerator * firstDenominator : operator === '-' ? firstNumerator * secondDenominator - secondNumerator * firstDenominator : operator === '*' ? firstNumerator * secondNumerator : firstNumerator * secondDenominator; const denominator = operator === '*' ? firstDenominator * secondDenominator : operator === '/' ? firstDenominator * secondNumerator : firstDenominator * secondDenominator; if (!denominator) throw new Error('Denominators cannot be zero.'); const divisor = gcd(numerator, denominator); return `${numerator / divisor} / ${denominator / divisor}`; })} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Calculate fraction</button></>;
    if (kind === 'invoice-generator') return <InvoiceGenerator />;
    if (kind === 'qr-logo-generator') return <QrLogoGenerator />;
    if (kind === 'favicon-generator') return <FaviconGenerator />;
    if (kind === 'pdf-fill-sign') return <PdfFillSign />;
    if (kind === 'pomodoro-timer') return <Pomodoro output={output} setOutput={setOutput} />;
    if (kind === 'file-checksum') return <FileChecksum />;
    if (kind === 'image-cropper') return <ImageCropper />;
    if (kind === 'pdf-page-cropper') return <PdfCropper />;
    return null;
  };

  return <ToolLayout title={definition.title} description={definition.description} seoDescription={definition.seo} path={`/tools/${kind}`} icon={Icon}><div className="space-y-3">{render()}{error && <p className="text-sm text-red-600">{error}</p>}{output && <pre className="mt-5 max-h-[28rem] overflow-auto whitespace-pre-wrap rounded-xl bg-slate-900 p-4 text-sm text-slate-100">{output}</pre>}</div></ToolLayout>;
}

function NumberField({ label, value, onChange }: { label: string; value?: string; onChange: (value: string) => void }) { return <label className="block text-sm font-medium text-slate-700">{label}<input type={label.toLowerCase().includes('url') ? 'url' : 'text'} value={value ?? ''} onChange={(event) => onChange(event.target.value)} className={inputClass} /></label>; }
function Pomodoro({ output, setOutput }: { output: string; setOutput: (value: string) => void }) { const [seconds, setSeconds] = useState(1500); const [running, setRunning] = useState(false); useEffect(() => { if (!running) return undefined; const timer = window.setInterval(() => setSeconds((current) => { if (current <= 1) { setRunning(false); return 0; } return current - 1; }), 1000); return () => window.clearInterval(timer); }, [running]); useEffect(() => setOutput(`${String(Math.floor(seconds / 60)).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`), [seconds, setOutput]); return <div className="text-center"><p className="text-6xl font-bold tabular-nums text-slate-800">{output}</p><div className="mt-6 flex justify-center gap-3"><button type="button" onClick={() => setRunning(!running)} className="rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">{running ? 'Pause' : 'Start'}</button><button type="button" onClick={() => { setRunning(false); setSeconds(1500); }} className="rounded-xl border border-slate-200 px-5 py-2.5 font-semibold text-slate-700">Reset</button></div></div>; }
function FileChecksum() { const [file, setFile] = useState<File | null>(null); const [hash, setHash] = useState(''); return <><input type="file" onChange={async (event) => { const selected = event.target.files?.[0]; if (!selected) return; setFile(selected); setHash(''); setHash(Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', await selected.arrayBuffer()))).map((byte) => byte.toString(16).padStart(2, '0')).join('')); }} className={inputClass} /><p className="mt-3 text-sm text-slate-500">{file ? file.name : 'Choose a file to calculate its SHA-256 checksum.'}</p>{hash && <pre className="mt-3 break-all whitespace-pre-wrap rounded-xl bg-slate-900 p-4 text-sm text-white">{hash}</pre>}</>; }
function ImageCropper() { const [file, setFile] = useState<File | null>(null); const [url, setUrl] = useState(''); const [crop, setCrop] = useState({ width: '800', height: '600' }); return <><input type="file" accept="image/*" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) { setFile(selected); setUrl(URL.createObjectURL(selected)); } }} className={inputClass} />{url && <img src={url} alt="Selected crop source" className="mt-4 max-h-64 w-full rounded-xl border object-contain" />}<div className="mt-4 grid gap-3 sm:grid-cols-2"><NumberField label="Crop width" value={crop.width} onChange={(value) => setCrop((current) => ({ ...current, width: value }))} /><NumberField label="Crop height" value={crop.height} onChange={(value) => setCrop((current) => ({ ...current, height: value }))} /></div><button type="button" disabled={!file} onClick={() => { if (!file) return; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = parseNumber(crop.width, image.width); canvas.height = parseNumber(crop.height, image.height); canvas.getContext('2d')?.drawImage(image, 0, 0, canvas.width, canvas.height, 0, 0, canvas.width, canvas.height); canvas.toBlob((blob) => blob && downloadBlob(blob, 'cropped-image.png'), 'image/png'); }; image.src = url; }} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Crop and download</button></>; }
function PdfCropper() { const [file, setFile] = useState<File | null>(null); const [margin, setMargin] = useState('24'); return <><input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className={inputClass} /><NumberField label="Margin to remove (points)" value={margin} onChange={setMargin} /><button type="button" disabled={!file} onClick={async () => { if (!file) return; const document = await PDFDocument.load(await file.arrayBuffer()); const points = Math.max(0, parseNumber(margin)); document.getPages().forEach((page) => { const width = page.getWidth(); const height = page.getHeight(); page.setCropBox(points, points, Math.max(1, width - points * 2), Math.max(1, height - points * 2)); }); downloadBytes(await document.save(), 'cropped-pages.pdf'); }} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Crop and download</button></>; }
function InvoiceGenerator() { const [values, setValues] = useState({ business: '', customer: '', item: 'Service', quantity: '1', rate: '0', tax: '0' }); const setField = (key: keyof typeof values, value: string) => setValues((current) => ({ ...current, [key]: value })); const subtotal = parseNumber(values.quantity) * parseNumber(values.rate); const total = subtotal * (1 + parseNumber(values.tax) / 100); return <><div className="grid gap-3 sm:grid-cols-2"><NumberField label="Your business" value={values.business} onChange={(value) => setField('business', value)} /><NumberField label="Customer" value={values.customer} onChange={(value) => setField('customer', value)} /><NumberField label="Item or service" value={values.item} onChange={(value) => setField('item', value)} /><NumberField label="Quantity" value={values.quantity} onChange={(value) => setField('quantity', value)} /><NumberField label="Rate" value={values.rate} onChange={(value) => setField('rate', value)} /><NumberField label="Tax %" value={values.tax} onChange={(value) => setField('tax', value)} /></div><div className="mt-5 rounded-xl border border-slate-200 p-5"><p className="font-semibold">{values.business || 'Your business'}</p><p className="mt-2 text-sm text-slate-500">Bill to: {values.customer || 'Customer'}</p><p className="mt-5 border-t border-slate-100 pt-4">{values.item}: {values.quantity} x {values.rate}</p><p className="mt-3 text-right text-xl font-bold">Total: {total.toFixed(2)}</p></div><button type="button" onClick={() => window.print()} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Print / Save PDF</button></>; }
function QrLogoGenerator() { const [text, setText] = useState('https://example.com'); const [logo, setLogo] = useState<string | null>(null); const [image, setImage] = useState<string | null>(null); return <><NumberField label="Text or URL" value={text} onChange={setText} /><input type="file" accept="image/*" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) setLogo(URL.createObjectURL(selected)); }} className={`${inputClass} mt-3`} /><button type="button" onClick={async () => { const qrBlob = await generateQrCodePng(text, { size: 600, errorCorrection: 'H' }); const qrUrl = URL.createObjectURL(qrBlob); const qrImage = new Image(); qrImage.onload = () => { const canvas = document.createElement('canvas'); canvas.width = 600; canvas.height = 600; const context = canvas.getContext('2d'); if (!context) return; context.drawImage(qrImage, 0, 0, 600, 600); if (logo) { const logoImage = new Image(); logoImage.onload = () => { context.fillStyle = '#ffffff'; context.fillRect(245, 245, 110, 110); context.drawImage(logoImage, 255, 255, 90, 90); canvas.toBlob((blob) => blob && (setImage(URL.createObjectURL(blob)), downloadBlob(blob, 'qr-code-with-logo.png')), 'image/png'); }; logoImage.src = logo; } else { canvas.toBlob((blob) => blob && (setImage(URL.createObjectURL(blob)), downloadBlob(blob, 'qr-code.png')), 'image/png'); } }; qrImage.src = qrUrl; }} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white">Generate QR code</button>{image && <img src={image} alt="QR code with logo" className="mt-5 h-64 w-64 rounded-xl border p-2" />}</>; }
function FaviconGenerator() { const [source, setSource] = useState<string | null>(null); return <><input type="file" accept="image/*" onChange={(event) => { const selected = event.target.files?.[0]; if (selected) setSource(URL.createObjectURL(selected)); }} className={inputClass} /><p className="mt-3 text-sm text-slate-500">Generate a 32px PNG favicon from your image.</p><button type="button" disabled={!source} onClick={() => { if (!source) return; const image = new Image(); image.onload = () => { const canvas = document.createElement('canvas'); canvas.width = 32; canvas.height = 32; canvas.getContext('2d')?.drawImage(image, 0, 0, 32, 32); canvas.toBlob((blob) => blob && downloadBlob(blob, 'favicon-32.png'), 'image/png'); }; image.src = source; }} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Download favicon</button></>; }
function PdfFillSign() { const [file, setFile] = useState<File | null>(null); const [text, setText] = useState('Signed by'); return <><input type="file" accept="application/pdf" onChange={(event) => setFile(event.target.files?.[0] ?? null)} className={inputClass} /><NumberField label="Text to place on first page" value={text} onChange={setText} /><button type="button" disabled={!file} onClick={async () => { if (!file) return; const document = await PDFDocument.load(await file.arrayBuffer()); const page = document.getPages()[0]; page.drawText(text, { x: 48, y: 48, size: 12 }); downloadBytes(await document.save(), 'filled-signed.pdf'); }} className="mt-4 rounded-xl bg-brand-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50">Add text and download</button></>; }
